# .travis.yml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2018–2019 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:
    - os: osx
      env:
        - JOB="macOS + Swift Package Manager"
      osx_image: xcode10.1
      script:
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job macos‐swift‐package‐manager"
    - os: osx
      env:
        - JOB="macOS + Xcode"
      osx_image: xcode10.1
      script:
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job macos‐xcode"
    - os: linux
      env:
        - JOB="Linux"
      dist: xenial
      script:
        - "export SWIFT_VERSION=4.2.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job linux"
    - os: linux
      env:
        - JOB="Miscellaneous"
      dist: xenial
      script:
        - "export SWIFT_VERSION=4.2.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job miscellaneous"
    - os: linux
      env:
        - JOB="Deployment"
        - secure: "UnR8vHpiMV+K/hw28327AUTPMi3Hz2l0lB4/kcMRacT3nklN8+PHCISUThkd+W1qy1fjHXjwcYvgIATzfhcZT6+AGT+Qn1O2nOJFs/6Y2XJvrhFOwvkSDh0JqcZYHNbsbpx4xk84nOV9/EHtNFHb9xLFT9cr0K+GaZfAHnDO5VLbUnSBqs0FxPDKv4P75lTmd3LbNfsPl3tfL/xDMCCcqf0zm5bO9JeRQVxTx8RWLe5q+Rw6a15IcFmFjptRdyjJmrDKIDAR/vNn2ytmfDwPlaz0a0Q1j5uH1/x1y6aIHVu+/2eLXEbm0s9hpPg+DOPUoNfrDLVqijpyXxAo6d/XAOb/yV6YYZhMUt5FgZ3936izSOAQ20JYrlf7fTX7IrfEq75fiLleEWs2YAvO/uUd8E0uICjpAW8vR2i90/mHqQHWCpRVET4OZjs8D8zibb4XBstBa6Ddj6ojGyo7N8rgdPztfiaml3FJ9JhNdFcG3JgOB1J1Bte8Ky+eOma5VFJeK8NpgZ+Bdi5QzSkmnBYoTKfZ1Ylq3rkcCUt9EDW0jYPtJ6vXbA6VnB80KI00t3869jsF6BDEzsCgxjcX4dSlWVVrhaU5bbI7a64HqoZx0x+0PKYS3RqHyx9YQfUTkjOoEIYz1Zv4kW4LU0+fO4D0kgWTVT9B2YOSqTgiDOJLLho="
      if: branch = master and (not type = pull_request)

      deploy:
        provider: pages
        local_dir: docs
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
      dist: xenial
      script:
        - "export SWIFT_VERSION=4.2.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job deployment"

cache:
  directories:
  - $HOME/Library/Caches/ca.solideogloria.Workspace
  - $HOME/.cache/ca.solideogloria.Workspace
