#if !canImport(ObjectiveC)
import XCTest

extension SDGSwiftConfigurationAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGSwiftConfigurationAPITests = [
        ("testConfiguration", testConfiguration),
        ("testConfigurationError", testConfigurationError),
        ("testLinuxMainGenerationCompatibility", testLinuxMainGenerationCompatibility),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGSwiftConfigurationAPITests.__allTests__SDGSwiftConfigurationAPITests),
    ]
}
#endif
