#if !canImport(ObjectiveC)
import XCTest

extension ReadMeExampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadMeExampleTests = [
        ("testReadMe", testReadMe),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReadMeExampleTests.__allTests__ReadMeExampleTests),
    ]
}
#endif
