/*
 Resources.swift

 This source file is part of the SDGSwift open source project.
 https://sdggiesbrecht.github.io/SDGSwift

 Copyright ©2018–2020 Jeremy David Giesbrecht and the SDGSwift project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}
internal typealias Ressourcen = Resources

extension Resources {
  internal static let package = Data(
    base64Encoded:
      "Ly8gc3dpZnQtdG9vbHMtdmVyc2lvbjpbKnRvb2xzIHZlcnNpb24qXQoKLyoKIFBhY2thZ2Uuc3dpZnQKCiBUaGlzIHNvdXJjZSBmaWxlIGlzIHBhcnQgb2YgdGhlIFNER1N3aWZ0IG9wZW4gc291cmNlIHByb2plY3QuCiBodHRwczovL3NkZ2dpZXNicmVjaHQuZ2l0aHViLmlvL1NER1N3aWZ0CgogQ29weXJpZ2h0IMKpMjAxOOKAkzIwMjAgSmVyZW15IERhdmlkIEdpZXNicmVjaHQgYW5kIHRoZSBTREdTd2lmdCBwcm9qZWN0IGNvbnRyaWJ1dG9ycy4KCiBTb2xpIERlbyBnbG9yaWEuCgogTGljZW5zZWQgdW5kZXIgdGhlIEFwYWNoZSBMaWNlbmNlLCBWZXJzaW9uIDIuMC4KIFNlZSBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAgZm9yIGxpY2VuY2UgaW5mb3JtYXRpb24uCiAqLwoKaW1wb3J0IFBhY2thZ2VEZXNjcmlwdGlvbgoKbGV0IHBhY2thZ2UgPSBQYWNrYWdlKAogIG5hbWU6ICJjb25maWd1cmUiLAogIHBsYXRmb3JtczogWwogICAgLm1hY09TKC52WyptYWNPUypdKQogIF0sCiAgZGVwZW5kZW5jaWVzOiBbCiAgICAucGFja2FnZShbKnBhY2thZ2UgbmFtZSpddXJsOiAiWypVUkwqXSIsIC5leGFjdCgiWyp2ZXJzaW9uKl0iKSksCiAgICBbKnBhY2thZ2VzKl0sCiAgXSwKICB0YXJnZXRzOiBbCiAgICAudGFyZ2V0KAogICAgICBuYW1lOiAiY29uZmlndXJlIiwKICAgICAgZGVwZW5kZW5jaWVzOiBbCiAgICAgICAgWypwcm9kdWN0Kl0sCiAgICAgICAgWypwcm9kdWN0cypdLAogICAgICBdCiAgICApCiAgXQopCg=="
  )!

}
