#if !canImport(ObjectiveC)
import XCTest

extension SDGSwiftAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGSwiftAPITests = [
        ("testBuild", testBuild),
        ("testGit", testGit),
        ("testGitError", testGitError),
        ("testLocalizations", testLocalizations),
        ("testPackage", testPackage),
        ("testPackageError", testPackageError),
        ("testPackageRepository", testPackageRepository),
        ("testSwiftCompiler", testSwiftCompiler),
        ("testSwiftCompilerError", testSwiftCompilerError),
        ("testVersion", testVersion),
    ]
}

extension SDGSwiftRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGSwiftRegressionTests = [
        ("testDynamicLinking", testDynamicLinking),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGSwiftAPITests.__allTests__SDGSwiftAPITests),
        testCase(SDGSwiftRegressionTests.__allTests__SDGSwiftRegressionTests),
    ]
}
#endif
