#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testBuild", testBuild),
        ("testGit", testGit),
        ("testGitError", testGitError),
        ("testLocalizations", testLocalizations),
        ("testPackage", testPackage),
        ("testPackageError", testPackageError),
        ("testPackageRepository", testPackageRepository),
        ("testSwiftCompiler", testSwiftCompiler),
        ("testSwiftCompilerError", testSwiftCompilerError),
        ("testVersion", testVersion),
    ]
}

extension RegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegressionTests = [
        ("testDependencyWarnings", testDependencyWarnings),
        ("testDynamicLinking", testDynamicLinking),
        ("testIgnoredFilesCheckIsStable", testIgnoredFilesCheckIsStable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
        testCase(RegressionTests.__allTests__RegressionTests),
    ]
}
#endif
