#if !canImport(ObjectiveC)
import XCTest

extension SDGSwiftPackageManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGSwiftPackageManagerTests = [
        ("testChangeDetection", testChangeDetection),
        ("testIgnoredFileDetection", testIgnoredFileDetection),
        ("testInitialization", testInitialization),
        ("testManifestLoading", testManifestLoading),
        ("testPackageGraphLoading", testPackageGraphLoading),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGSwiftPackageManagerTests.__allTests__SDGSwiftPackageManagerTests),
    ]
}
#endif
