#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testAPIParsing", testAPIParsing),
        ("testCallout", testCallout),
        ("testCodeFragmentSyntax", testCodeFragmentSyntax),
        ("testCoreLibraries", testCoreLibraries),
        ("testCSS", testCSS),
        ("testExtension", testExtension),
        ("testFunctionalSyntaxScanner", testFunctionalSyntaxScanner),
        ("testLineDeveloperCommentSyntax", testLineDeveloperCommentSyntax),
        ("testLineDocumentationCommentSyntax", testLineDocumentationCommentSyntax),
        ("testLocations", testLocations),
        ("testPackageDocumentation", testPackageDocumentation),
        ("testParsing", testParsing),
        ("testTokenSyntax", testTokenSyntax),
        ("testTree", testTree),
        ("testTriviaPiece", testTriviaPiece),
    ]
}

extension InternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InternalTests = [
        ("testEmptySyntax", testEmptySyntax),
        ("testExtendedSyntaxContext", testExtendedSyntaxContext),
        ("testLocalizations", testLocalizations),
        ("testStringLiteral", testStringLiteral),
        ("testTokenNormalization", testTokenNormalization),
    ]
}

extension RegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegressionTests = [
        ("testContinuedCallout", testContinuedCallout),
        ("testMarkdownEntity", testMarkdownEntity),
        ("testMarkdownQuotation", testMarkdownQuotation),
        ("testPackageDeclaration", testPackageDeclaration),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
        testCase(InternalTests.__allTests__InternalTests),
        testCase(RegressionTests.__allTests__RegressionTests),
    ]
}
#endif
