/*
 Resources.swift

 This source file is part of the SDGSwift open source project.
 https://sdggiesbrecht.github.io/SDGSwift

 Copyright ©2018 Jeremy David Giesbrecht and the SDGSwift project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}

extension Resources {
    static let source = Data(base64Encoded: "LyoKIFNvdXJjZS5zd2lmdAoKIFRoaXMgc291cmNlIGZpbGUgaXMgcGFydCBvZiB0aGUgU0RHU3dpZnQgb3BlbiBzb3VyY2UgcHJvamVjdC4KIGh0dHBzOi8vc2RnZ2llc2JyZWNodC5naXRodWIuaW8vU0RHU3dpZnQvU0RHU3dpZnQKCiBDb3B5cmlnaHQgwqkyMDE4IEplcmVteSBEYXZpZCBHaWVzYnJlY2h0IGFuZCB0aGUgU0RHU3dpZnQgcHJvamVjdCBjb250cmlidXRvcnMuCgogU29saSBEZW8gZ2xvcmlhLgoKIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5jZSwgVmVyc2lvbiAyLjAuCiBTZWUgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wIGZvciBsaWNlbmNlIGluZm9ybWF0aW9uLgogKi8KCmZ1bmMgY292ZXJlZCgpIC0+IEJvb2wgewogICAgcmV0dXJuIHRydWUKfQoKZnVuYyBub3RDb3ZlcmVkKCkgLT4gQm9vbCB7CiAgICByZXR1cm4gdHJ1ZQp9Cgp2YXIgYHN3aXRjaGAgPSBmYWxzZQpmdW5jIGJyYW5jaGluZygpIC0+IEJvb2wgewogICAgaWYgYHN3aXRjaGAgewogICAgICAgIHJldHVybiB0cnVlCiAgICB9IGVsc2UgewogICAgICAgIHJldHVybiB0cnVlCiAgICB9Cn0KCnZhciDwn5iAID0gZmFsc2UKZnVuYyB3aXRoU3VwcGxlbWVudGFsUGxhbmVDaGFyYWN0ZXJzKCkgLT4gQm9vbCB7CiAgICBpZiDwn5iAIHsKICAgICAgICByZXR1cm4gdHJ1ZQogICAgfQogICAgcmV0dXJuIGZhbHNlCn0KCmZ1bmMgYWNjZXB0Q2xvc3VyZShfIGNsb3N1cmU6ICgpIC0+IFZvaWQpIHsKICAgIGNsb3N1cmUoKQp9CmZ1bmMgdXNlQ2xvc3VyZSgpIHsKICAgIGFjY2VwdENsb3N1cmUoewogICAgICAgIGlmIGBzd2l0Y2hgIHsKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgfQogICAgfSkKfQo=")!
    static let tests = Data(base64Encoded: "LyoKIFRlc3RzLnN3aWZ0CgogVGhpcyBzb3VyY2UgZmlsZSBpcyBwYXJ0IG9mIHRoZSBTREdTd2lmdCBvcGVuIHNvdXJjZSBwcm9qZWN0LgogaHR0cHM6Ly9zZGdnaWVzYnJlY2h0LmdpdGh1Yi5pby9TREdTd2lmdC9TREdTd2lmdAoKIENvcHlyaWdodCDCqTIwMTggSmVyZW15IERhdmlkIEdpZXNicmVjaHQgYW5kIHRoZSBTREdTd2lmdCBwcm9qZWN0IGNvbnRyaWJ1dG9ycy4KCiBTb2xpIERlbyBnbG9yaWEuCgogTGljZW5zZWQgdW5kZXIgdGhlIEFwYWNoZSBMaWNlbmNlLCBWZXJzaW9uIDIuMC4KIFNlZSBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAgZm9yIGxpY2VuY2UgaW5mb3JtYXRpb24uCiAqLwoKaW1wb3J0IFhDVGVzdApAdGVzdGFibGUgaW1wb3J0IE1vY2sKCmNsYXNzIENvdmVyYWdlVGVzdHMgOiBYQ1Rlc3RDYXNlIHsKCiAgICBmdW5jIHRlc3RDb3ZlcmFnZSgpIHsKICAgICAgICBfID0gY292ZXJlZCgpCgogICAgICAgIGBzd2l0Y2hgID0gZmFsc2UKICAgICAgICBfID0gYnJhbmNoaW5nKCkKICAgICAgICB1c2VDbG9zdXJlKCkKICAgICAgICBgc3dpdGNoYCA9IHRydWUKICAgICAgICBfID0gYnJhbmNoaW5nKCkKICAgICAgICB1c2VDbG9zdXJlKCkKCiAgICAgICAgXyA9IHdpdGhTdXBwbGVtZW50YWxQbGFuZUNoYXJhY3RlcnMoKQogICAgfQp9Cg==")!

}
