/*
 Resources.swift

 This source file is part of the SDGSwift open source project.
 https://sdggiesbrecht.github.io/SDGSwift

 Copyright ©2018–2019 Jeremy David Giesbrecht and the SDGSwift project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}

extension Resources {
    static let source = Data(base64Encoded: "LyoKIFNvdXJjZS5zd2lmdAoKIFRoaXMgc291cmNlIGZpbGUgaXMgcGFydCBvZiB0aGUgU0RHU3dpZnQgb3BlbiBzb3VyY2UgcHJvamVjdC4KIGh0dHBzOi8vc2RnZ2llc2JyZWNodC5naXRodWIuaW8vU0RHU3dpZnQKCiBDb3B5cmlnaHQgwqkyMDE44oCTMjAxOSBKZXJlbXkgRGF2aWQgR2llc2JyZWNodCBhbmQgdGhlIFNER1N3aWZ0IHByb2plY3QgY29udHJpYnV0b3JzLgoKIFNvbGkgRGVvIGdsb3JpYS4KCiBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2VuY2UsIFZlcnNpb24gMi4wLgogU2VlIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMCBmb3IgbGljZW5jZSBpbmZvcm1hdGlvbi4KICovCgpmdW5jIGNvdmVyZWQoKSAtPiBCb29sIHsKICAgIHJldHVybiB0cnVlCn0KCmZ1bmMgbm90Q292ZXJlZCgpIC0+IEJvb2wgewogICAgcmV0dXJuIHRydWUKfQoKdmFyIGBzd2l0Y2hgID0gZmFsc2UKZnVuYyBicmFuY2hpbmcoKSAtPiBCb29sIHsKICAgIGlmIGBzd2l0Y2hgIHsKICAgICAgICByZXR1cm4gdHJ1ZQogICAgfSBlbHNlIHsKICAgICAgICByZXR1cm4gdHJ1ZQogICAgfQp9Cgp2YXIg8J+YgCA9IGZhbHNlCmZ1bmMgd2l0aFN1cHBsZW1lbnRhbFBsYW5lQ2hhcmFjdGVycygpIC0+IEJvb2wgewogICAgaWYg8J+YgCB7CiAgICAgICAgcmV0dXJuIHRydWUKICAgIH0KICAgIHJldHVybiBmYWxzZQp9CgpmdW5jIGFjY2VwdENsb3N1cmUoXyBjbG9zdXJlOiAoKSAtPiBWb2lkKSB7CiAgICBjbG9zdXJlKCkKfQpmdW5jIHVzZUNsb3N1cmUoKSB7CiAgICBhY2NlcHRDbG9zdXJlKHsKICAgICAgICBpZiBgc3dpdGNoYCB7CiAgICAgICAgICAgIHJldHVybgogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIHJldHVybgogICAgICAgIH0KICAgIH0pCn0K")!
    static let tests = Data(base64Encoded: "LyoKIFRlc3RzLnN3aWZ0CgogVGhpcyBzb3VyY2UgZmlsZSBpcyBwYXJ0IG9mIHRoZSBTREdTd2lmdCBvcGVuIHNvdXJjZSBwcm9qZWN0LgogaHR0cHM6Ly9zZGdnaWVzYnJlY2h0LmdpdGh1Yi5pby9TREdTd2lmdAoKIENvcHlyaWdodCDCqTIwMTjigJMyMDE5IEplcmVteSBEYXZpZCBHaWVzYnJlY2h0IGFuZCB0aGUgU0RHU3dpZnQgcHJvamVjdCBjb250cmlidXRvcnMuCgogU29saSBEZW8gZ2xvcmlhLgoKIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5jZSwgVmVyc2lvbiAyLjAuCiBTZWUgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wIGZvciBsaWNlbmNlIGluZm9ybWF0aW9uLgogKi8KCmltcG9ydCBYQ1Rlc3QKQHRlc3RhYmxlIGltcG9ydCBNb2NrCgpjbGFzcyBDb3ZlcmFnZVRlc3RzIDogWENUZXN0Q2FzZSB7CgogICAgZnVuYyB0ZXN0Q292ZXJhZ2UoKSB7CiAgICAgICAgXyA9IGNvdmVyZWQoKQoKICAgICAgICBgc3dpdGNoYCA9IGZhbHNlCiAgICAgICAgXyA9IGJyYW5jaGluZygpCiAgICAgICAgdXNlQ2xvc3VyZSgpCiAgICAgICAgYHN3aXRjaGAgPSB0cnVlCiAgICAgICAgXyA9IGJyYW5jaGluZygpCiAgICAgICAgdXNlQ2xvc3VyZSgpCgogICAgICAgIF8gPSB3aXRoU3VwcGxlbWVudGFsUGxhbmVDaGFyYWN0ZXJzKCkKICAgIH0KfQo=")!

}
