#if !canImport(ObjectiveC)
import XCTest

extension SDGXcodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGXcodeTests = [
        ("testLinuxMainGenerationCompatibility", testLinuxMainGenerationCompatibility),
        ("testXcode", testXcode),
        ("testXcodeCoverage", testXcodeCoverage),
        ("testXcodeError", testXcodeError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGXcodeTests.__allTests__SDGXcodeTests),
    ]
}
#endif
