#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testDependencyWarnings", testDependencyWarnings),
        ("testXcode", testXcode),
        ("testXcodeCoverage", testXcodeCoverage),
        ("testXcodeError", testXcodeError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
    ]
}
#endif
