# CentOS.yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2021 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: CentOS

on: [push, pull_request]

jobs:
  CentOS_5_4:
    name: CentOS (Swift 5.4)
    runs-on: ubuntu-20.04
    container: swift:5.4.0-centos8
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: CentOS‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        yum install --assumeyes \
          ncurses-devel \
          sqlite-devel
    - name: Install Workspace dependencies
      shell: bash
      run: |
        set -x
        yum install --assumeyes \
          curl
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test --enable-test-discovery
    - name: Grant permission to cache
      shell: bash
      run: |
        set -x
        chmod -R a+rwx .
