# iOS.yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2021 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: iOS

on: [push, pull_request]

jobs:
  iOS_5_4:
    name: iOS (Swift 5.4)
    runs-on: macos-11.0
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: macOS‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Set Xcode up
      shell: bash
      run: |
        set -x
        sudo xcode-select -switch /Applications/Xcode_12.5.app
        xcodebuild -version
        swift --version
    - name: Validate
      shell: bash
      run: |
        set -x
        export TARGETING_IOS=true
        xcodebuild test -destination 'name=iPhone 12' -scheme SDGSwift-Package
