# macOS (Swift 5.3).yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2021 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: macOS (Swift 5.3)

on: [push, pull_request]

jobs:
  macOS_Swift_5_3:
    name: macOS (Swift 5.3)
    runs-on: macos-11.0
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: macOS‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Set Xcode up
      shell: bash
      run: |
        set -x
        sudo xcode-select -switch /Applications/Xcode_12.4.app
        xcodebuild -version
        swift --version
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
