# Ubuntu.yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2021–2023 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.7 (Ubuntu)

on: [push, pull_request]

jobs:
  Swift_5_7_Ubuntu:
    name: Swift 5.7 (Ubuntu)
    runs-on: ubuntu-20.04
    container: swift:5.7.3-focal
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Repair Git
      shell: bash
      run: |
        set -x
        git config --global --add safe.directory '*'
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            libncurses-dev \
            libsqlite3-dev
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
