# macOS.yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2021–2022 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.7 (macOS)

on: [push, pull_request]

jobs:
  macOS:
    name: Swift 5.7 (macOS)
    runs-on: macos-12
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set Xcode up
      shell: bash
      run: |
        set -x
        sudo xcode-select -switch /Applications/Xcode_14.app
        xcodebuild -version
        swift --version
    - name: Validate
      shell: bash
      run: |
        set -x
        swift build
