name: Swift 5.8 (Ubuntu)

on: [push, pull_request]

jobs:
  Swift_5_8_Ubuntu:
    name: Swift 5.8 (Ubuntu)
    runs-on: ubuntu-20.04
    container: swift:5.8.0-focal
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Cache Workspace
      uses: actions/cache@v2
      with:
        key: Ubuntu‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Repair Git
      shell: bash
      run: |
        set -x
        git config --global --add safe.directory '*'
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            libncurses-dev \
            libsqlite3-dev
    - name: Install Workspace dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            curl
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
    - name: Grant permission to cache
      shell: bash
      run: |
        set -x
        chmod -R a+rwx .
